### ISSUE TITLE
Evaluation of Text2Img models with DETR

### ISSUE THREAD

**Issue by TonyLianLong** [j-min/DallEval#3]
Great work on building this benchmark for text to image models!

In [this page](https://github.com/j-min/DallEval/tree/main/paintskills), the evaluation of text to image models with DETR is still "coming soon". Is there any plan to release the procedure for text to image model evaluation?

**Comment by j-min** [comment]
Hi @TonyLianLong, thanks for your interest! I updated the [DETR checkpoint](https://huggingface.co/j-min/PaintSkills-DETR-R101-DC5) and let the [evaluation script](https://github.com/j-min/DallEval/blob/main/paintskills/detr/evaluate_skill.py) automatically downloads the checkpoint.
